services:
  app:
    build:
      context: .
      args:
        NEXT_PUBLIC_THEME: ${NEXT_PUBLIC_THEME:-cordel}
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data

  caddy:
    image: caddy:2
    restart: unless-stopped
    depends_on: [app]
    environment:
      GATE_USER: ${GATE_USER:?defina GATE_USER no .env}
      GATE_HASH: ${GATE_HASH:?defina GATE_HASH no .env}
      GATE_USER_B: ${GATE_USER_B:?defina GATE_USER_B no .env}
      GATE_USER_C: ${GATE_USER_C:?defina GATE_USER_C no .env}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
